In [1]:
import numpy as np
array = np.array([1,2,3,4,5])
c = array.tolist()
print(c)

[1, 2, 3, 4, 5]


In [1]:
import numpy as np

array = np.array([[1,2,3],[4,5,6],[7,8,9]])
sum = np.trace(array)
print(sum)

15


In [1]:
import numpy as np
new_array= np.array([[3,4],[5,6],[7,8]])
x = int(input("enter a value"))
print("value bigger then ", x,":",new_array[new_array>x])

enter a value4
value bigger then  4 : [5 6 7 8]


In [2]:
import numpy as np
array1 = np.array([[1,2],[3,4],[5,6]])
array2 = np.array([[7,8],[9,10],[11,12]])

array3 = array1 + array2
print(array3)

[[ 8 10]
 [12 14]
 [16 18]]


In [3]:
import numpy as np
array1 = np.array([[1,2],[3,4],[5,6]])
print(array1)
x =np.mean(array1, axis=1, dtype=float)
print( x )

[[1 2]
 [3 4]
 [5 6]]
[1.5 3.5 5.5]
